const flatArray = [
  {parentId: 0, id: 1, name: 'Дети', children: true},
  {parentId: 0, id: 29, name: 'Подростки', children: true},
  {parentId: 0, id: 30, name: 'Женщины', children: true},
  {parentId: 0, id: 31, name: 'Взрослые', children: true},
  {parentId: 0, id: 32, name: 'Пожилые', children: true},
  {parentId: 0, id: 33, name: 'Семьи', children: true},
  {parentId: 0, id: 37, name: 'Народности', children: true},
  {parentId: 0, id: 38, name: 'Населенные пункты', children: true},
  {parentId: 0, id: 41, name: 'Животные', children: true},
  {parentId: 0, id: 42, name: 'Экология', children: true},
  {parentId: 0, id: 34, name: 'Профессиональные сообщества', children: false},
  {parentId: 0, id: 35, name: 'Местные сообщества', children: false},
  {parentId: 0, id: 36, name: 'Религиозные общины', children: false},
  {parentId: 0, id: 39, name: 'Некоммерческий сектор', children: false},
  {parentId: 0, id: 40, name: 'Общество', children: false},
  {parentId: 1, id: 2, name: 'Имеющие редкие заболевания', children: true},
  {parentId: 1, id: 15, name: 'Имеющие тяжелые заболевания', children: true},
  {parentId: 1, id: 19, name: 'С инвалидностью', children: false},
  {parentId: 1, id: 20, name: 'ВИЧ-положительные', children: false},
  {parentId: 1, id: 21, name: 'Мигранты и беженцы', children: false},
  {parentId: 1, id: 22, name: 'Нуждающиеся в лечении', children: false},
  {parentId: 1, id: 23, name: 'Онкобольные', children: false},
  {parentId: 1, id: 24, name: 'Паллиативные больные', children: false},
  {parentId: 1, id: 25, name: 'Перенесшие насилие', children: false},
  {parentId: 1, id: 26, name: 'Перенесшие травлю', children: false},
  {parentId: 1, id: 27, name: 'Пропавшие без вести и потерявшиеся', children: false},
  {parentId: 1, id: 28, name: 'Сироты', children: false},
  {parentId: 2, id: 3, name: 'Spina Bifida', children: false},
  {parentId: 2, id: 4, name: 'Буллёзный эпидермолиз', children: false},
  {parentId: 2, id: 5, name: 'Гемофилия', children: false},
  {parentId: 2, id: 6, name: 'Миодистрофия Дюшенна', children: false},
  {parentId: 2, id: 7, name: 'Муковисцидоз', children: false},
  {parentId: 2, id: 8, name: 'Несовершенный остеогенез', children: false},
  {parentId: 2, id: 9, name: 'Синдром Дауна', children: false},
  {parentId: 2, id: 10, name: 'Синдром Лежена', children: false},
  {parentId: 2, id: 11, name: 'Синдром Ретта', children: false},
  {parentId: 2, id: 12, name: 'Эктодермальная ангидротическая дисплазия', children: false},
  {parentId: 15, id: 16, name: 'Тяжелое заболевание 1', children: false},
  {parentId: 15, id: 17, name: 'Тяжелое заболевание 2', children: false},
  {parentId: 15, id: 18, name: 'Тяжелое заболевание 3', children: false},
];

export {flatArray};
